### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by Karanveer-logiciel** [DmcSDK/cordova-plugin-mediaPicker#35]
Hello @DmcSDK 
  
Can you help me to install this plugin for android 

My cordova cli - 8.0.0
      cordova android - 7.0.0 

i am getting this error when i try to install this plugin 

`UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin git+https://github.com/DmcSDK/cordova-plugin-mediaPicker.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
    at C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:173:37
    at _rejected (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:864:24)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:808:41)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:137:13)
    at flush (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:176:11)
(node:10644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10644) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by DmcSDK** [comment]
@Karanveer-logiciel  Check your connection

**Comment by DmcSDK** [comment]
@Karanveer-logiciel  i test cordova 8.0 and android 7.0.1 work ok
